forge "http://forge.puppetlabs.com"

mod 'puppetlabs/apt'
mod 'puppetlabs/stdlib'
mod 'puppetlabs/mysql'
mod 'puppetlabs/postgresql'
mod 'puppetlabs/vcsrepo'
mod 'puppetmaster', :git => 'https://github.com/fsalum/puppet-puppetmaster.git'
mod 'dhoppe/hosts'
mod 'puppetlabs/puppetdb'
mod 'puppetlabs/apache'
mod 'puppetlabs/ruby'
mod 'puppetlabs/passenger'
mod 'puppetlabs/dashboard'
