forge "http://forge.puppetlabs.com"

mod 'puppetlabs/apt'
mod 'puppetlabs/stdlib'
mod 'puppetlabs/firewall'
mod 'puppetlabs/mysql'
mod 'puppetlabs/postgresql'
mod 'puppetlabs/dashboard'
mod 'puppetmaster', :git => 'https://github.com/fsalum/puppet-puppetmaster.git'
mod 'dhoppe/hosts'
mod 'python', :git => 'https://github.com/stankevich/puppet-python.git'
mod 'puppetlabs/vcsrepo'
mod 'puppetlabs/puppetdb'
mod 'puppetlabs/apache'
mod 'puppetlabs/ruby'
mod 'puppetlabs/passenger'
mod 'upstart', :git => "https://github.com/bison/puppet-upstart.git"
